version: 2
updates:
  # Keep Github Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "12:30"
  - package-ecosystem: "pip"
    directory: "/helpers"
    schedule:
      interval: "daily"
      time: "12:00"
  - package-ecosystem: "docker"
    directory: "/helpers"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
  - package-ecosystem: "docker"
    directory: "/mailbox"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
  - package-ecosystem: "docker"
    directory: "/relay"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
  - package-ecosystem: "docker"
    directory: "/wormhole"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
