version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/mailbox"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
    reviewers:
      - "LeastAuthority/magic-wormhole"
  - package-ecosystem: "docker"
    directory: "/relay"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
    reviewers:
      - "LeastAuthority/magic-wormhole"
  - package-ecosystem: "docker"
    directory: "/wormhole"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:00"
    reviewers:
      - "LeastAuthority/magic-wormhole"
