version: "3.3"
services:
  mailbox:
    image: leastauthority/magic-wormhole-mailbox
    build:
      context: ./mailbox
    environment:
      - MW_MAILBOX_PORT=${MW_MAILBOX_PORT:-4000}
    volumes:
      - "./mailbox_database:/db"
  relay:
    image: leastauthority/magic-wormhole-relay
    build:
      context: ./relay
    environment:
      - MW_RELAY_PORT=${MW_RELAY_PORT:-4001}
      - MW_RELAY_WS_PORT=${MW_RELAY_WS_PORT:-4200}
    volumes:
      - "./relay_database:/db"
