
---
name: Docker Nix Images

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-nix.yml'
      - 'nixpkgs.json'
      - '*.nix'
      - '*/*.nix'
  pull_request:
    branches:    
      - main
    paths:
      - '.github/workflows/docker-nix.yml'
      - 'nixpkgs.json'
      - '*.nix'
      - '*/*.nix'

jobs:
  build-nix:
    name: Build Docker images with Nix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11

    - name: Build the Docker images with nix
      run: |
        nix-build | while read IMG; do
          docker load --input ${IMG}
        done

    - name: List images
      run: docker images

    - name: Extract requirements
      run: |
        docker run --rm -t --entrypoint python -v $(pwd)/helpers:/tmp/helpers \
        magic-wormhole:0.12.0-python39-nix2111 /tmp/helpers/list-dependencies.py \
        | grep -E "python3\.9" \
        | sed -r -e 's/python3.9-//' -e 's/-([0-9])/==\1/' \
        | grep -vE '\-dev$' \
        | sort \
        > requirements.txt

    - name: Scan images
      uses: pypa/gh-action-pip-audit@v1.0.0
      with:
        inputs: requirements.txt
