---
name: Magic Wormhole Mailbox Server Image

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - directory: mailbox
            image: leastauthority/magic-wormhole-mailbox
            version: ac91c3a
            platforms: linux/arm64/v8,linux/amd64
          - directory: relay
            image: leastauthority/magic-wormhole-relay
            version: db48e91
            platforms: linux/arm64/v8,linux/amd64
          - directory: wormhole
            image: leastauthority/magic-wormhole
            version: 52ee3ce
            platforms: linux/arm64/v8,linux/amd64
    steps:
    - uses: actions/checkout@v3
    - name: Determine target tag
      id: target
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_type: ${{ github.ref_type }}"
        if [ ${{ github.ref_type }} == 'branch' ]; then
        echo "target_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
        echo "target_tag=$(git describe --tags --always)" >> $GITHUB_ENV
        fi
        cat $GITHUB_ENV
    - name: Create Builder
      run: docker buildx create --name mwbuilder --bootstrap --use
    - name: Build the Docker image in cache
      working-directory: ./${{ matrix.target.directory }}
      run: docker buildx build . --file Dockerfile --tag ${{ matrix.target.image }}:${{ env.target_tag }} --build-arg VERSION_TAG=${{ matrix.target.version }} --platform ${{ matrix.target.platforms }}
    - name: List images
      run: docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    - name: Push to Docker Hub
      working-directory: ./${{ matrix.target.directory }}
      run: docker buildx build --push . --file Dockerfile --tag ${{ matrix.target.image }}:${{ env.target_tag }} --build-arg VERSION_TAG=${{ matrix.target.version }} --platform ${{ matrix.target.platforms }}
      if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    - name: Push to Docker Hub latest
      working-directory: ./${{ matrix.target.directory }}
      run: docker buildx build --push . --file Dockerfile --tag ${{ matrix.target.image }}:latest --build-arg VERSION_TAG=${{ matrix.target.version }} --platform ${{ matrix.target.platforms }}
      if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
